// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

// Protobuf Java Version: 3.25.3
package dev.jeshwanth.observatory.telemetry;

public interface DeviceMetricsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:telemetry.DeviceMetrics)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>.telemetry.DeviceType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.telemetry.DeviceType type = 2;</code>
   * @return The type.
   */
  dev.jeshwanth.observatory.telemetry.DeviceType getType();

  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  long getTimestampMs();

  /**
   * <code>double cpu_percent = 4;</code>
   * @return The cpuPercent.
   */
  double getCpuPercent();

  /**
   * <code>double memory_percent = 5;</code>
   * @return The memoryPercent.
   */
  double getMemoryPercent();

  /**
   * <code>double battery_health = 6;</code>
   * @return The batteryHealth.
   */
  double getBatteryHealth();

  /**
   * <code>double network_latency_ms = 7;</code>
   * @return The networkLatencyMs.
   */
  double getNetworkLatencyMs();

  /**
   * <code>bool os_compliant = 8;</code>
   * @return The osCompliant.
   */
  boolean getOsCompliant();

  /**
   * <code>string region = 9;</code>
   * @return The region.
   */
  java.lang.String getRegion();
  /**
   * <code>string region = 9;</code>
   * @return The bytes for region.
   */
  com.google.protobuf.ByteString
      getRegionBytes();
}
