// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

// Protobuf Java Version: 3.25.3
package dev.jeshwanth.observatory.telemetry;

public interface IngestResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:telemetry.IngestResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool accepted = 1;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
