// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

// Protobuf Java Version: 3.25.3
package dev.jeshwanth.observatory.telemetry;

/**
 * Protobuf type {@code telemetry.DeviceMetrics}
 */
public final class DeviceMetrics extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:telemetry.DeviceMetrics)
    DeviceMetricsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceMetrics.newBuilder() to construct.
  private DeviceMetrics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceMetrics() {
    deviceId_ = "";
    type_ = 0;
    region_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceMetrics();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.jeshwanth.observatory.telemetry.Telemetry.internal_static_telemetry_DeviceMetrics_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.jeshwanth.observatory.telemetry.Telemetry.internal_static_telemetry_DeviceMetrics_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.jeshwanth.observatory.telemetry.DeviceMetrics.class, dev.jeshwanth.observatory.telemetry.DeviceMetrics.Builder.class);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deviceId_ = "";
  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  @java.lang.Override
  public java.lang.String getDeviceId() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceId_ = s;
      return s;
    }
  }
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceIdBytes() {
    java.lang.Object ref = deviceId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private int type_ = 0;
  /**
   * <code>.telemetry.DeviceType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.telemetry.DeviceType type = 2;</code>
   * @return The type.
   */
  @java.lang.Override public dev.jeshwanth.observatory.telemetry.DeviceType getType() {
    dev.jeshwanth.observatory.telemetry.DeviceType result = dev.jeshwanth.observatory.telemetry.DeviceType.forNumber(type_);
    return result == null ? dev.jeshwanth.observatory.telemetry.DeviceType.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMP_MS_FIELD_NUMBER = 3;
  private long timestampMs_ = 0L;
  /**
   * <code>int64 timestamp_ms = 3;</code>
   * @return The timestampMs.
   */
  @java.lang.Override
  public long getTimestampMs() {
    return timestampMs_;
  }

  public static final int CPU_PERCENT_FIELD_NUMBER = 4;
  private double cpuPercent_ = 0D;
  /**
   * <code>double cpu_percent = 4;</code>
   * @return The cpuPercent.
   */
  @java.lang.Override
  public double getCpuPercent() {
    return cpuPercent_;
  }

  public static final int MEMORY_PERCENT_FIELD_NUMBER = 5;
  private double memoryPercent_ = 0D;
  /**
   * <code>double memory_percent = 5;</code>
   * @return The memoryPercent.
   */
  @java.lang.Override
  public double getMemoryPercent() {
    return memoryPercent_;
  }

  public static final int BATTERY_HEALTH_FIELD_NUMBER = 6;
  private double batteryHealth_ = 0D;
  /**
   * <code>double battery_health = 6;</code>
   * @return The batteryHealth.
   */
  @java.lang.Override
  public double getBatteryHealth() {
    return batteryHealth_;
  }

  public static final int NETWORK_LATENCY_MS_FIELD_NUMBER = 7;
  private double networkLatencyMs_ = 0D;
  /**
   * <code>double network_latency_ms = 7;</code>
   * @return The networkLatencyMs.
   */
  @java.lang.Override
  public double getNetworkLatencyMs() {
    return networkLatencyMs_;
  }

  public static final int OS_COMPLIANT_FIELD_NUMBER = 8;
  private boolean osCompliant_ = false;
  /**
   * <code>bool os_compliant = 8;</code>
   * @return The osCompliant.
   */
  @java.lang.Override
  public boolean getOsCompliant() {
    return osCompliant_;
  }

  public static final int REGION_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object region_ = "";
  /**
   * <code>string region = 9;</code>
   * @return The region.
   */
  @java.lang.Override
  public java.lang.String getRegion() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      region_ = s;
      return s;
    }
  }
  /**
   * <code>string region = 9;</code>
   * @return The bytes for region.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRegionBytes() {
    java.lang.Object ref = region_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      region_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
    }
    if (type_ != dev.jeshwanth.observatory.telemetry.DeviceType.MAC_ENDPOINT.getNumber()) {
      output.writeEnum(2, type_);
    }
    if (timestampMs_ != 0L) {
      output.writeInt64(3, timestampMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(cpuPercent_) != 0) {
      output.writeDouble(4, cpuPercent_);
    }
    if (java.lang.Double.doubleToRawLongBits(memoryPercent_) != 0) {
      output.writeDouble(5, memoryPercent_);
    }
    if (java.lang.Double.doubleToRawLongBits(batteryHealth_) != 0) {
      output.writeDouble(6, batteryHealth_);
    }
    if (java.lang.Double.doubleToRawLongBits(networkLatencyMs_) != 0) {
      output.writeDouble(7, networkLatencyMs_);
    }
    if (osCompliant_ != false) {
      output.writeBool(8, osCompliant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, region_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(deviceId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
    }
    if (type_ != dev.jeshwanth.observatory.telemetry.DeviceType.MAC_ENDPOINT.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, type_);
    }
    if (timestampMs_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestampMs_);
    }
    if (java.lang.Double.doubleToRawLongBits(cpuPercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, cpuPercent_);
    }
    if (java.lang.Double.doubleToRawLongBits(memoryPercent_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(5, memoryPercent_);
    }
    if (java.lang.Double.doubleToRawLongBits(batteryHealth_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(6, batteryHealth_);
    }
    if (java.lang.Double.doubleToRawLongBits(networkLatencyMs_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, networkLatencyMs_);
    }
    if (osCompliant_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, osCompliant_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(region_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, region_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.jeshwanth.observatory.telemetry.DeviceMetrics)) {
      return super.equals(obj);
    }
    dev.jeshwanth.observatory.telemetry.DeviceMetrics other = (dev.jeshwanth.observatory.telemetry.DeviceMetrics) obj;

    if (!getDeviceId()
        .equals(other.getDeviceId())) return false;
    if (type_ != other.type_) return false;
    if (getTimestampMs()
        != other.getTimestampMs()) return false;
    if (java.lang.Double.doubleToLongBits(getCpuPercent())
        != java.lang.Double.doubleToLongBits(
            other.getCpuPercent())) return false;
    if (java.lang.Double.doubleToLongBits(getMemoryPercent())
        != java.lang.Double.doubleToLongBits(
            other.getMemoryPercent())) return false;
    if (java.lang.Double.doubleToLongBits(getBatteryHealth())
        != java.lang.Double.doubleToLongBits(
            other.getBatteryHealth())) return false;
    if (java.lang.Double.doubleToLongBits(getNetworkLatencyMs())
        != java.lang.Double.doubleToLongBits(
            other.getNetworkLatencyMs())) return false;
    if (getOsCompliant()
        != other.getOsCompliant()) return false;
    if (!getRegion()
        .equals(other.getRegion())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TIMESTAMP_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestampMs());
    hash = (37 * hash) + CPU_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getCpuPercent()));
    hash = (37 * hash) + MEMORY_PERCENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMemoryPercent()));
    hash = (37 * hash) + BATTERY_HEALTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getBatteryHealth()));
    hash = (37 * hash) + NETWORK_LATENCY_MS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getNetworkLatencyMs()));
    hash = (37 * hash) + OS_COMPLIANT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOsCompliant());
    hash = (37 * hash) + REGION_FIELD_NUMBER;
    hash = (53 * hash) + getRegion().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.jeshwanth.observatory.telemetry.DeviceMetrics prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code telemetry.DeviceMetrics}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:telemetry.DeviceMetrics)
      dev.jeshwanth.observatory.telemetry.DeviceMetricsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.jeshwanth.observatory.telemetry.Telemetry.internal_static_telemetry_DeviceMetrics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.jeshwanth.observatory.telemetry.Telemetry.internal_static_telemetry_DeviceMetrics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.jeshwanth.observatory.telemetry.DeviceMetrics.class, dev.jeshwanth.observatory.telemetry.DeviceMetrics.Builder.class);
    }

    // Construct using dev.jeshwanth.observatory.telemetry.DeviceMetrics.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      deviceId_ = "";
      type_ = 0;
      timestampMs_ = 0L;
      cpuPercent_ = 0D;
      memoryPercent_ = 0D;
      batteryHealth_ = 0D;
      networkLatencyMs_ = 0D;
      osCompliant_ = false;
      region_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.jeshwanth.observatory.telemetry.Telemetry.internal_static_telemetry_DeviceMetrics_descriptor;
    }

    @java.lang.Override
    public dev.jeshwanth.observatory.telemetry.DeviceMetrics getDefaultInstanceForType() {
      return dev.jeshwanth.observatory.telemetry.DeviceMetrics.getDefaultInstance();
    }

    @java.lang.Override
    public dev.jeshwanth.observatory.telemetry.DeviceMetrics build() {
      dev.jeshwanth.observatory.telemetry.DeviceMetrics result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.jeshwanth.observatory.telemetry.DeviceMetrics buildPartial() {
      dev.jeshwanth.observatory.telemetry.DeviceMetrics result = new dev.jeshwanth.observatory.telemetry.DeviceMetrics(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.jeshwanth.observatory.telemetry.DeviceMetrics result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.deviceId_ = deviceId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestampMs_ = timestampMs_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cpuPercent_ = cpuPercent_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.memoryPercent_ = memoryPercent_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.batteryHealth_ = batteryHealth_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.networkLatencyMs_ = networkLatencyMs_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.osCompliant_ = osCompliant_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.region_ = region_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.jeshwanth.observatory.telemetry.DeviceMetrics) {
        return mergeFrom((dev.jeshwanth.observatory.telemetry.DeviceMetrics)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.jeshwanth.observatory.telemetry.DeviceMetrics other) {
      if (other == dev.jeshwanth.observatory.telemetry.DeviceMetrics.getDefaultInstance()) return this;
      if (!other.getDeviceId().isEmpty()) {
        deviceId_ = other.deviceId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTimestampMs() != 0L) {
        setTimestampMs(other.getTimestampMs());
      }
      if (other.getCpuPercent() != 0D) {
        setCpuPercent(other.getCpuPercent());
      }
      if (other.getMemoryPercent() != 0D) {
        setMemoryPercent(other.getMemoryPercent());
      }
      if (other.getBatteryHealth() != 0D) {
        setBatteryHealth(other.getBatteryHealth());
      }
      if (other.getNetworkLatencyMs() != 0D) {
        setNetworkLatencyMs(other.getNetworkLatencyMs());
      }
      if (other.getOsCompliant() != false) {
        setOsCompliant(other.getOsCompliant());
      }
      if (!other.getRegion().isEmpty()) {
        region_ = other.region_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              deviceId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              timestampMs_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 33: {
              cpuPercent_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            case 41: {
              memoryPercent_ = input.readDouble();
              bitField0_ |= 0x00000010;
              break;
            } // case 41
            case 49: {
              batteryHealth_ = input.readDouble();
              bitField0_ |= 0x00000020;
              break;
            } // case 49
            case 57: {
              networkLatencyMs_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 64: {
              osCompliant_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 74: {
              region_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object deviceId_ = "";
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceId() {
      deviceId_ = getDefaultInstance().getDeviceId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string device_id = 1;</code>
     * @param value The bytes for deviceId to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deviceId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.telemetry.DeviceType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.telemetry.DeviceType type = 2;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.telemetry.DeviceType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public dev.jeshwanth.observatory.telemetry.DeviceType getType() {
      dev.jeshwanth.observatory.telemetry.DeviceType result = dev.jeshwanth.observatory.telemetry.DeviceType.forNumber(type_);
      return result == null ? dev.jeshwanth.observatory.telemetry.DeviceType.UNRECOGNIZED : result;
    }
    /**
     * <code>.telemetry.DeviceType type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(dev.jeshwanth.observatory.telemetry.DeviceType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.telemetry.DeviceType type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000002);
      type_ = 0;
      onChanged();
      return this;
    }

    private long timestampMs_ ;
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return The timestampMs.
     */
    @java.lang.Override
    public long getTimestampMs() {
      return timestampMs_;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @param value The timestampMs to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampMs(long value) {

      timestampMs_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp_ms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestampMs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestampMs_ = 0L;
      onChanged();
      return this;
    }

    private double cpuPercent_ ;
    /**
     * <code>double cpu_percent = 4;</code>
     * @return The cpuPercent.
     */
    @java.lang.Override
    public double getCpuPercent() {
      return cpuPercent_;
    }
    /**
     * <code>double cpu_percent = 4;</code>
     * @param value The cpuPercent to set.
     * @return This builder for chaining.
     */
    public Builder setCpuPercent(double value) {

      cpuPercent_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double cpu_percent = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuPercent() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cpuPercent_ = 0D;
      onChanged();
      return this;
    }

    private double memoryPercent_ ;
    /**
     * <code>double memory_percent = 5;</code>
     * @return The memoryPercent.
     */
    @java.lang.Override
    public double getMemoryPercent() {
      return memoryPercent_;
    }
    /**
     * <code>double memory_percent = 5;</code>
     * @param value The memoryPercent to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryPercent(double value) {

      memoryPercent_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>double memory_percent = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryPercent() {
      bitField0_ = (bitField0_ & ~0x00000010);
      memoryPercent_ = 0D;
      onChanged();
      return this;
    }

    private double batteryHealth_ ;
    /**
     * <code>double battery_health = 6;</code>
     * @return The batteryHealth.
     */
    @java.lang.Override
    public double getBatteryHealth() {
      return batteryHealth_;
    }
    /**
     * <code>double battery_health = 6;</code>
     * @param value The batteryHealth to set.
     * @return This builder for chaining.
     */
    public Builder setBatteryHealth(double value) {

      batteryHealth_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>double battery_health = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBatteryHealth() {
      bitField0_ = (bitField0_ & ~0x00000020);
      batteryHealth_ = 0D;
      onChanged();
      return this;
    }

    private double networkLatencyMs_ ;
    /**
     * <code>double network_latency_ms = 7;</code>
     * @return The networkLatencyMs.
     */
    @java.lang.Override
    public double getNetworkLatencyMs() {
      return networkLatencyMs_;
    }
    /**
     * <code>double network_latency_ms = 7;</code>
     * @param value The networkLatencyMs to set.
     * @return This builder for chaining.
     */
    public Builder setNetworkLatencyMs(double value) {

      networkLatencyMs_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>double network_latency_ms = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNetworkLatencyMs() {
      bitField0_ = (bitField0_ & ~0x00000040);
      networkLatencyMs_ = 0D;
      onChanged();
      return this;
    }

    private boolean osCompliant_ ;
    /**
     * <code>bool os_compliant = 8;</code>
     * @return The osCompliant.
     */
    @java.lang.Override
    public boolean getOsCompliant() {
      return osCompliant_;
    }
    /**
     * <code>bool os_compliant = 8;</code>
     * @param value The osCompliant to set.
     * @return This builder for chaining.
     */
    public Builder setOsCompliant(boolean value) {

      osCompliant_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool os_compliant = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearOsCompliant() {
      bitField0_ = (bitField0_ & ~0x00000080);
      osCompliant_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object region_ = "";
    /**
     * <code>string region = 9;</code>
     * @return The region.
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        region_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string region = 9;</code>
     * @return The bytes for region.
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string region = 9;</code>
     * @param value The region to set.
     * @return This builder for chaining.
     */
    public Builder setRegion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      region_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string region = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearRegion() {
      region_ = getDefaultInstance().getRegion();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string region = 9;</code>
     * @param value The bytes for region to set.
     * @return This builder for chaining.
     */
    public Builder setRegionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      region_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:telemetry.DeviceMetrics)
  }

  // @@protoc_insertion_point(class_scope:telemetry.DeviceMetrics)
  private static final dev.jeshwanth.observatory.telemetry.DeviceMetrics DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.jeshwanth.observatory.telemetry.DeviceMetrics();
  }

  public static dev.jeshwanth.observatory.telemetry.DeviceMetrics getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceMetrics>
      PARSER = new com.google.protobuf.AbstractParser<DeviceMetrics>() {
    @java.lang.Override
    public DeviceMetrics parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeviceMetrics> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceMetrics> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.jeshwanth.observatory.telemetry.DeviceMetrics getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

