// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: proto/telemetry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryGateway_IngestMetrics_FullMethodName = "/telemetry.TelemetryGateway/IngestMetrics"
	TelemetryGateway_IngestStream_FullMethodName  = "/telemetry.TelemetryGateway/IngestStream"
)

// TelemetryGatewayClient is the client API for TelemetryGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelemetryGatewayClient interface {
	IngestMetrics(ctx context.Context, in *DeviceMetrics, opts ...grpc.CallOption) (*IngestResponse, error)
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMetrics, IngestResponse], error)
}

type telemetryGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryGatewayClient(cc grpc.ClientConnInterface) TelemetryGatewayClient {
	return &telemetryGatewayClient{cc}
}

func (c *telemetryGatewayClient) IngestMetrics(ctx context.Context, in *DeviceMetrics, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, TelemetryGateway_IngestMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telemetryGatewayClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeviceMetrics, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryGateway_ServiceDesc.Streams[0], TelemetryGateway_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeviceMetrics, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryGateway_IngestStreamClient = grpc.BidiStreamingClient[DeviceMetrics, IngestResponse]

// TelemetryGatewayServer is the server API for TelemetryGateway service.
// All implementations must embed UnimplementedTelemetryGatewayServer
// for forward compatibility.
type TelemetryGatewayServer interface {
	IngestMetrics(context.Context, *DeviceMetrics) (*IngestResponse, error)
	IngestStream(grpc.BidiStreamingServer[DeviceMetrics, IngestResponse]) error
	mustEmbedUnimplementedTelemetryGatewayServer()
}

// UnimplementedTelemetryGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryGatewayServer struct{}

func (UnimplementedTelemetryGatewayServer) IngestMetrics(context.Context, *DeviceMetrics) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IngestMetrics not implemented")
}
func (UnimplementedTelemetryGatewayServer) IngestStream(grpc.BidiStreamingServer[DeviceMetrics, IngestResponse]) error {
	return status.Errorf(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedTelemetryGatewayServer) mustEmbedUnimplementedTelemetryGatewayServer() {}
func (UnimplementedTelemetryGatewayServer) testEmbeddedByValue()                          {}

// UnsafeTelemetryGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryGatewayServer will
// result in compilation errors.
type UnsafeTelemetryGatewayServer interface {
	mustEmbedUnimplementedTelemetryGatewayServer()
}

func RegisterTelemetryGatewayServer(s grpc.ServiceRegistrar, srv TelemetryGatewayServer) {
	// If the following call pancis, it indicates UnimplementedTelemetryGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryGateway_ServiceDesc, srv)
}

func _TelemetryGateway_IngestMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceMetrics)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelemetryGatewayServer).IngestMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelemetryGateway_IngestMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelemetryGatewayServer).IngestMetrics(ctx, req.(*DeviceMetrics))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelemetryGateway_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryGatewayServer).IngestStream(&grpc.GenericServerStream[DeviceMetrics, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryGateway_IngestStreamServer = grpc.BidiStreamingServer[DeviceMetrics, IngestResponse]

// TelemetryGateway_ServiceDesc is the grpc.ServiceDesc for TelemetryGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telemetry.TelemetryGateway",
	HandlerType: (*TelemetryGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IngestMetrics",
			Handler:    _TelemetryGateway_IngestMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _TelemetryGateway_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/telemetry.proto",
}
