// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

// Protobuf Java Version: 3.25.3
package dev.jeshwanth.observatory.telemetry;

/**
 * Protobuf enum {@code telemetry.DeviceType}
 */
public enum DeviceType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>MAC_ENDPOINT = 0;</code>
   */
  MAC_ENDPOINT(0),
  /**
   * <code>EDGE_NODE = 1;</code>
   */
  EDGE_NODE(1),
  /**
   * <code>IOT_SENSOR = 2;</code>
   */
  IOT_SENSOR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MAC_ENDPOINT = 0;</code>
   */
  public static final int MAC_ENDPOINT_VALUE = 0;
  /**
   * <code>EDGE_NODE = 1;</code>
   */
  public static final int EDGE_NODE_VALUE = 1;
  /**
   * <code>IOT_SENSOR = 2;</code>
   */
  public static final int IOT_SENSOR_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static DeviceType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static DeviceType forNumber(int value) {
    switch (value) {
      case 0: return MAC_ENDPOINT;
      case 1: return EDGE_NODE;
      case 2: return IOT_SENSOR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<DeviceType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      DeviceType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<DeviceType>() {
          public DeviceType findValueByNumber(int number) {
            return DeviceType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return dev.jeshwanth.observatory.telemetry.Telemetry.getDescriptor().getEnumTypes().get(0);
  }

  private static final DeviceType[] VALUES = values();

  public static DeviceType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private DeviceType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:telemetry.DeviceType)
}

