// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

// Protobuf Java Version: 3.25.3
package dev.jeshwanth.observatory.telemetry;

public final class Telemetry {
  private Telemetry() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_telemetry_DeviceMetrics_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_telemetry_DeviceMetrics_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_telemetry_IngestResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_telemetry_IngestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017telemetry.proto\022\ttelemetry\"\344\001\n\rDeviceM" +
      "etrics\022\021\n\tdevice_id\030\001 \001(\t\022#\n\004type\030\002 \001(\0162" +
      "\025.telemetry.DeviceType\022\024\n\014timestamp_ms\030\003" +
      " \001(\003\022\023\n\013cpu_percent\030\004 \001(\001\022\026\n\016memory_perc" +
      "ent\030\005 \001(\001\022\026\n\016battery_health\030\006 \001(\001\022\032\n\022net" +
      "work_latency_ms\030\007 \001(\001\022\024\n\014os_compliant\030\010 " +
      "\001(\010\022\016\n\006region\030\t \001(\t\"3\n\016IngestResponse\022\020\n" +
      "\010accepted\030\001 \001(\010\022\017\n\007message\030\002 \001(\t*=\n\nDevi" +
      "ceType\022\020\n\014MAC_ENDPOINT\020\000\022\r\n\tEDGE_NODE\020\001\022" +
      "\016\n\nIOT_SENSOR\020\0022\241\001\n\020TelemetryGateway\022D\n\r" +
      "IngestMetrics\022\030.telemetry.DeviceMetrics\032" +
      "\031.telemetry.IngestResponse\022G\n\014IngestStre" +
      "am\022\030.telemetry.DeviceMetrics\032\031.telemetry" +
      ".IngestResponse(\0010\001B0\n#dev.jeshwanth.obs" +
      "ervatory.telemetryP\001Z\007./protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_telemetry_DeviceMetrics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_telemetry_DeviceMetrics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_telemetry_DeviceMetrics_descriptor,
        new java.lang.String[] { "DeviceId", "Type", "TimestampMs", "CpuPercent", "MemoryPercent", "BatteryHealth", "NetworkLatencyMs", "OsCompliant", "Region", });
    internal_static_telemetry_IngestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_telemetry_IngestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_telemetry_IngestResponse_descriptor,
        new java.lang.String[] { "Accepted", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
